### ISSUE TITLE
No Album Art

### ISSUE THREAD

**Issue by johnallen3d** [GuardKenzie/miniplayer#1]
Thanks for this project! I'm a kitty + mpd user so this is perfect for me! 😄 

I've just installed, configured and fired up the player. The general functionality seems to be working well however I'm not seeing album art. I've confirmed that the track I'm listening to has artwork embedded. I've also updated my configuration to point at my music directory (mirroring mpd/mpc config):

```conf
[player]
music_directory = "~/Music/iTunes/iTunes Music/Music/"
```

**Comment by GuardKenzie** [comment]
Thank you for your interest in my project. 

Remove the quotes from the beginning and end of your music directory and it should work.

This is what your config should look like:
```
​[player]
music_directory = ~/Music/iTunes/iTunes Music/Music/
```

**Comment by johnallen3d** [comment]
I thought I tried that first but I guess not. Works like a charm, thanks!
