### ISSUE TITLE
The player errors on startup if there is no config file present

### ISSUE THREAD

**Issue by onlyvip** [GuardKenzie/miniplayer#13]
i have all the necessary dependencies installed via pip3
i have installed miniplayer from pip3 by 
sudo pip3 install miniplayer.
its installed successfully but when i run it i get following error
![image](https://user-images.githubusercontent.com/76858994/119248403-8bdaad80-bbae-11eb-9065-c36bf4a3efcc.png)

**Comment by onlyvip** [comment]
im sorry i had copied the config file but it was not renamed

**Comment by GuardKenzie** [comment]
You were correct to open an issue. The player should be able to run even if there isn't a config file present.
I have managed to reproduce this on my machine and will look into it.

**Comment by GuardKenzie** [comment]
Fixed with df28cac.

**Comment by GuardKenzie** [comment]
The fix is now live on PyPi.
