### ISSUE TITLE
Puts some beats on! Message

### ISSUE THREAD

**Issue by c0dysharma** [GuardKenzie/miniplayer#16]
Miniplayer just shows Puts some beats on message. Mpd service is up and running other mpd clients are also working fine.
System Info:
OS: Manjaro Linux x86_64
Kernel: 5.12.9-1-MANJARO
Shell: zsh 5.8
WM: i3

my miniplayer default config

```
[player]
music_directory = ~/Music
font_width = 11
font_height = 24
image_method = pixcat
volume_step = 5
auto_close = false
album_art_only = false
show_playlist = true

[mpd]
host = localhost
port = 6600
```

mpd conifg

```
music_directory "/Music"
playlist_directory "/.config/mpd/playlists"
db_file "/.config/mpd/database"
log_file "syslog"
state_file "/.config/mpd/state"
bind_to_address "127.0.0.1"
port "6600"
auto_update "yes"
input {
plugin "curl"
}
audio_output {
type "pulse"
name "My Pulse Output"
}
```

Also tried changing locahost to 127.0.0.1 in miniplayer config as well  and other mpd clients like ncmpcpp also working!

_Originally posted by @c0dysharma in https://github.com/GuardKenzie/miniplayer/issues/5#issuecomment-873330784_

**Comment by GuardKenzie** [comment]
Could you please tell me if you are running python 64bit and which version of `python-mpd2` you are using?

After that, verify that music is playing and miniplayer still only displays the "Put some beats on!" message and post the output of the following script:

```python
from mpd import MPDClient
c = MPDClient()
c.connect("localhost", 6600)
print(c.status())
```

**Comment by c0dysharma** [comment]
Hey so just discovered I need to create and play a playlist from another mpd client. To be able to later change playback from miniplayer.

Is it how it supposed to work? Actually am new to mpd pardon me but If this the way a line readme stating clearly would be great.

**Comment by GuardKenzie** [comment]
Yes, that is the intended use case at the moment. I am (slowly) working on a library browser but it will take a while, sorry.
