### ISSUE TITLE
XDG paths support

### ISSUE THREAD

**Issue by tye-singwa** [GuardKenzie/miniplayer#25]
Hi! 
I've checked source code, and it seems that it uses hardcoded config path.
It would be nice if miniplayer read config from [XDG config dir](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead.
Thanks!

**Comment by GuardKenzie** [comment]
Implemented with 2d8d5ebfde01063757be35c0fe59ed4b6037a0ce
