### ISSUE TITLE
A config option to show only the album artwork

### ISSUE THREAD

**Issue by vide0hanz** [GuardKenzie/miniplayer#6]
Hey there, 

Love the simplicity of this program! I'm primarily using this as a scratchpad window to quickly show album artwork, and I feel like it is a really nice companion program to something like `ncmpcpp`. 

It might be neat to add a config option to show the artwork only; no progress indicator/track info. 

Perhaps the track information can be used as the window title itself while there is an active track playing, rather than simply displaying 'miniplayer'. 

I'm thinking this addition might be potentially useful for people who use a multiplexer with other minimal mpd clients -- i.e. a tmux session with individual panes for ncmpcpp, miniplayer, etc. - this way they could simply use miniplayer as a way to display artwork only, and still retain the ability to use it as a standalone application with track changing, pausing, etc. via the keybinds. 

Before I take a stab at it myself I thought I'd pitch the idea to see what you think?

**Comment by GuardKenzie** [comment]
This is a neat idea; I like it!

**Comment by vide0hanz** [comment]
> It might even be nice to have a keybind to toggle between the two configurations as well as a default state specifiable in the config file.

Yeah that sounds nice. Maybe `if keyChar == "i":` for "info"? 

On that note, how feasible is it to allow for configurable bindings? I tried to override the defaults within the source but it didn't work, but I'm not very familiar with python. 

I also had the idea of only allowing miniplayer to run if there is an active playlist, and force it to exit when the playlist concludes. With nothing to display it turns into kind of a pointless window :)

**Comment by GuardKenzie** [comment]
> Yeah that sounds nice. Maybe `if keyChar == "i":` for "info"?

Yeah, that should do the trick.

> On that note, how feasible is it to allow for configurable bindings? I tried to override the defaults within the source but it didn't work, but I'm not very familiar with python.

That requires a bit more work but it is something I've been wanting to get to for a while. I've opened a new issue for that #7.

> I also had the idea of only allowing miniplayer to run if there is an active playlist, and force it to exit when the playlist concludes. With nothing to display it turns into kind of a pointless window :)

This sounds like a good config option as well. It wouldn't be nice to have it like that by default in case you have a playlist that ends and you just want to add to it later and don't want to have to relaunch the program as well. You could open a new issue for this.

**Comment by GuardKenzie** [comment]
This has been implemented as of 7628bb37f77c4a50d65de45782d3feb593230aa7
