### ISSUE TITLE
Configurable keybinds

### ISSUE THREAD

**Issue by GuardKenzie** [GuardKenzie/miniplayer#7]
Configurable keybinds would be nice to implement.

**Comment by GuardKenzie** [comment]
This has been implemented as of da7655cf5180b32df89fc516afdab44971a843d9.

**Comment by vide0hanz** [comment]
Just wanted to say these simple additions are quite nice. Configurable keybinds plus the info binding make operating this thing with one hand dead simple and intuitive (I bound J and K for next/prev tracks, for example). Thanks!
